version: '3.4'

## PLEASE provide values for relevant environment variables (e.g, GIT_USER) in an accompanying .env file
## the .env file will not be checked in to version control

services:
  db:
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-example}
      TZ: "Europe/London"
    stdin_open: true
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - "oe-db:/var/lib/mysql"
    command:
      # Changing log_file_size to allow lightning image processing of larger document image events
      - "--innodb_log_file_size"
      - "128M"
      # disable binary logging (as not needed for development, but logs MUST be enabled for production)
      - "--disable-log-bin"
      # Uncomment the next line for testing, or to use 10.4 with older versions of OE (prior to v4.0)
      # - "--sql-mode=NO_ENGINE_SUBSTITUTION,NO_AUTO_CREATE_USER"

  web_5:
    image: appertaopeneyes/web:latest
    container_name: openeyes_web_5
    environment:
      GIT_USER: ${GIT_USER:?'Please set your github user id in .env file'}
      TZ: 'Europe/London'
      UID: '1'
      GID: '1'
      OE_MODE: 'DEV'
      OE_INSTITUTION_CODE: NEW
      OE_PORTAL_URI: ${OE_PORTAL_URI}
      OE_PORTAL_EXTERNAL_URI: ${OE_PORTAL_EXTERNAL_URI}
      OE_PORTAL_USERNAME: ${OE_PORTAL_USERNAME}
      OE_PORTAL_PASSWORD: ${OE_PORTAL_PASSWORD}
      OE_PORTAL_CLIENT_ID: ${OE_PORTAL_USERNAME}
      OE_PORTAL_CLIENT_SECRET: ${OE_PORTAL_CLIENT_SECRET}
      OE_PORTAL_ENABLED: "FALSE"
      SSH_SERVER_ENABLE: "TRUE"
      DATABASE_HOST: "db"
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-example}
      PHPI_TEST_SETTING: test-123
      WAIT_HOSTS_TIMEOUT: "300" # It can take a while for the mariadb container to initialise on first run
      ENABLE_CRON: "FALSE" # Remove this for live installs
      AUTH_SOURCE: "" # Set it to SAML or OIDC for SSO or leave it blank
      SSO_BASE_URL: "" # Base URL for SAML Single Sign-On
      SSO_ENTITY_ID: "" # Entity ID URL obtained from SAML Single Sign-On portal
      SSO_APP_EMBED_LINK: "" # embed link obtained from SAML Single Sign-On portal
      SSO_PROVIDER_URL: "" # OpenID Connect Provider (OP) that will send the token
      SSO_CLIENT_ID: "" # Client ID given by OIDC Provider
      SSO_ISSUER_URL: "" # URL for custom Authorization Server
      SSO_REDIRECT_URL: "" # Absolute URI where OIDC token will be sent
      SSO_RESPONSE_TYPE: "code" # Response type - can be [code id_token token]
      SSO_IMPLICIT_FLOW: "FALSE" # Implicit flow - true or false
    secrets:
      - source: SSH_PRIVATE_KEY
      - source: SSH_AUTHORIZED_KEYS
      - source: SSO_CERTIFICATE
      - source: SSO_CLIENT_SECRET
      - source: SODIUM_CRYPTO_KEY
    ports:
      - "80:80"
      - "22:22"
    tmpfs:
      - /tmp
    stdin_open: true
    tty: true
    volumes:
      - "oe-web:/var/www/openeyes"
      # Following is useful when using VS COde remote for development
      - "php5_vscode:/root/.vscode-server"
    depends_on:
      - db
    hostname: oe-web-php5

#  web_7:
#    image: appertaopeneyes/web:php7
#    container_name: openeyes_web_7
#    environment:
#      GIT_USER: ${GIT_USER:?'Please set your github user id in .env file'}
#      TZ: 'Europe/London'
#      UID: '1'
#      GID: '1'
#      OE_MODE: 'DEV'
#      OE_INSTITUTION_CODE: NEW
#      OE_PORTAL_URI: ${OE_PORTAL_URI}
#      OE_PORTAL_EXTERNAL_URI: ${OE_PORTAL_EXTERNAL_URI}
#      OE_PORTAL_USERNAME: ${OE_PORTAL_USERNAME}
#      OE_PORTAL_PASSWORD: ${OE_PORTAL_PASSWORD}
#      OE_PORTAL_CLIENT_ID: ${OE_PORTAL_USERNAME}
#      OE_PORTAL_CLIENT_SECRET: ${OE_PORTAL_CLIENT_SECRET}
#      OE_PORTAL_ENABLED: "FALSE"
#      SSH_SERVER_ENABLE: "TRUE"
#      DATABASE_HOST: "db"
#      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-example}
#      PHPI_TEST_SETTING: test-123
#      WAIT_HOSTS: "web_5:80" # Wait for web_5 to startup first - this prevents both containers trying to clone at the same time on first run
#      WAIT_HOSTS_TIMEOUT: "3000" # It can take quite a while for web 5 to start on first run, so we need a long time-out
#      WAIT_SLEEP_INTERVAL: "3" # reduces the number of messages sent to the log while waiting for web_5 to complete its first run
#      ENABLE_CRON: "FALSE" # Remove this for live installs
#      SSO_BASE_URL: "" # Base URL for SSO
#      SSO_ENTITY_ID: "" # Entity ID URL obtained from okta portal
#      SSO_APP_EMBED_LINK: "" # embed link obtained from okta portal
#      AUTH_SOURCE: "" # Set it to SAML or OIDC for SSO or leave it blank
#      SSO_BASE_URL: "" # Base URL for SAML Single Sign-On
#      SSO_ENTITY_ID: "" # Entity ID URL obtained from SAML Single Sign-On portal
#      SSO_APP_EMBED_LINK: "" # embed link obtained from SAML Single Sign-On portal
#      SSO_PROVIDER_URL: "" # OpenID Connect Provider (OP) that will send the token
#      SSO_CLIENT_ID: "" # Client ID given by OIDC Provider
#      SSO_CLIENT_SECRET: "" # Client Secret given by OIDC Provider
#      SSO_ISSUER_URL: "" # URL for custom Authorization Server
#      SSO_REDIRECT_URL: "" # Absolute URI where OIDC token will be sent
#      SSO_RESPONSE_TYPE: "code" # Response type - can be [code id_token token]
#      SSO_IMPLICIT_FLOW: "FALSE" # Implicit flow - true or false
#    secrets:
#      - source: SSH_PRIVATE_KEY
#      - source: SSH_AUTHORIZED_KEYS
#      - source: SSO_CERTIFICATE
#      - source: SSO_CLIENT_SECRET
#      - source: SODIUM_CRYPTO_KEY
#    ports:
#      - "7777:80"
#      - "22:22"
#    stdin_open: true
#    tty: true
#    volumes:
#      - "oe-web:/var/www/openeyes"
#      # Following is useful when using VS COde remote for development
#      - "php7_vscode:/root/.vscode-server"
#    depends_on:
#     - "db"
#     - "web_5"
#    hostname: oe-web-php7

volumes:
  oe-web:
  oe-db:
  php5_vscode:
  php7_vscode:

secrets:
  SSH_PRIVATE_KEY:
    file: ~/.ssh/id_rsa
  SSH_AUTHORIZED_KEYS:
    file: ~/.ssh/id_rsa.pub
  SSO_CERTIFICATE:
    file: sso.cert
  SSO_CLIENT_SECRET:
    file: oe_client_secret
  SODIUM_CRYPTO_KEY:
    file: key
